apiVersion: v1
kind: Service
metadata:
  name: fuse-springboot-service
  labels:
    app: fuse-springboot
spec:
  selector:
    app: fuse-springboot
    group: org.mycompany
    version: 1.0.0-SNAPSHOT
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080