---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
    labels:
      app: fuse-springboot
      expose: "true"
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.mycompany
    name: fuse-springboot-service
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fuse-springboot
      group: org.mycompany
      version: 1.0.0-SNAPSHOT
      provider: fabric8
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse-springboot&var-version=1.0.0-SNAPSHOT
    labels:
      app: fuse-springboot
      group: org.mycompany
      version: 1.0.0-SNAPSHOT
      provider: fabric8
    name: fuse-springboot-deployment
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: fuse-springboot
      group: org.mycompany
      version: 1.0.0-SNAPSHOT
      provider: fabric8
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse-springboot&var-version=1.0.0-SNAPSHOT
        labels:
          app: fuse-springboot
          group: org.mycompany
          version: 1.0.0-SNAPSHOT
          provider: fabric8
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: springboot-fuse:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: camel-app
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: fuse-springboot
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.mycompany
    name: fuse-springboot-route
  spec:
    path: /
    port:
      targetPort: 8080
    to:
      kind: Service
      name: fuse-springboot-service
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: fuse-springboot
      expose: "true"
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.mycompany
    name: fuse-springboot-service
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: fuse-springboot-service
