---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: location-soap2rest
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.mycompany
    name: location-soap2rest
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: location-soap2rest
      provider: fabric8
      group: org.mycompany
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=location-soap2rest&var-version=1.0.0-SNAPSHOT
    labels:
      app: location-soap2rest
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.mycompany
    name: location-soap2rest
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: location-soap2rest
        provider: fabric8
        group: org.mycompany
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=location-soap2rest&var-version=1.0.0-SNAPSHOT
        labels:
          app: location-soap2rest
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: org.mycompany
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: mycompany/location-soap2rest:snapshot-210113-163923-0851
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
